package dev.gaphunter.certcompanion.cert

import org.junit.AfterClass
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.BeforeClass
import org.junit.Test
import java.io.File
import java.nio.file.Files

/**
 * Fixtures are REAL certificates/keystores generated by the JDK's own
 * keytool (the same tool bundled with every JDK, guaranteed to be sitting
 * next to whatever `java` runs this test at `$java.home/bin/keytool`) rather
 * than hand-built byte arrays or JDK-internal certificate-builder APIs —
 * more stable across JDK versions and exercises the parser against exactly
 * the kind of file real users have.
 */
class CertParserTest {

    companion object {
        private const val STORE_PASSWORD = "gap-hunter-test-pw"

        private lateinit var tempDir: File
        private lateinit var keytool: String

        private lateinit var validCertBytes: ByteArray
        private lateinit var expiredCertBytes: ByteArray
        private lateinit var soonCertBytes: ByteArray
        private lateinit var bundlePemBytes: ByteArray
        private lateinit var jksBytes: ByteArray
        private lateinit var p12Bytes: ByteArray

        @BeforeClass
        @JvmStatic
        fun generateFixtures() {
            val javaHome = System.getProperty("java.home")
            val exeName = if (System.getProperty("os.name").lowercase().contains("win")) "keytool.exe" else "keytool"
            keytool = File(File(javaHome, "bin"), exeName).absolutePath

            tempDir = Files.createTempDirectory("cert-companion-test").toFile()

            runKeytool(
                "-genkeypair", "-alias", "valid", "-keyalg", "RSA", "-keysize", "2048",
                "-validity", "3650", "-keystore", "valid.jks", "-storetype", "JKS",
                "-storepass", STORE_PASSWORD, "-keypass", STORE_PASSWORD,
                "-dname", "CN=Valid Test Cert, OU=Gap Hunter Labs, O=Gap Hunter Labs, L=Bogota, ST=Bogota, C=CO",
            )
            runKeytool(
                "-genkeypair", "-alias", "expired", "-keyalg", "RSA", "-keysize", "2048",
                "-startdate", "-400d", "-validity", "30", "-keystore", "expired.jks", "-storetype", "JKS",
                "-storepass", STORE_PASSWORD, "-keypass", STORE_PASSWORD,
                "-dname", "CN=Expired Test Cert, OU=Gap Hunter Labs, O=Gap Hunter Labs, L=Bogota, ST=Bogota, C=CO",
            )
            runKeytool(
                "-genkeypair", "-alias", "soon", "-keyalg", "RSA", "-keysize", "2048",
                "-startdate", "-1d", "-validity", "10", "-keystore", "soon.jks", "-storetype", "JKS",
                "-storepass", STORE_PASSWORD, "-keypass", STORE_PASSWORD,
                "-dname", "CN=Expiring Soon Test Cert, OU=Gap Hunter Labs, O=Gap Hunter Labs, L=Bogota, ST=Bogota, C=CO",
            )
            runKeytool(
                "-genkeypair", "-alias", "p12alias", "-keyalg", "RSA", "-keysize", "2048",
                "-validity", "3650", "-keystore", "test.p12", "-storetype", "PKCS12",
                "-storepass", STORE_PASSWORD, "-keypass", STORE_PASSWORD,
                "-dname", "CN=PKCS12 Test Cert, OU=Gap Hunter Labs, O=Gap Hunter Labs, L=Bogota, ST=Bogota, C=CO",
            )

            runKeytool("-exportcert", "-alias", "valid", "-keystore", "valid.jks", "-storepass", STORE_PASSWORD, "-rfc", "-file", "valid.pem")
            runKeytool("-exportcert", "-alias", "soon", "-keystore", "soon.jks", "-storepass", STORE_PASSWORD, "-rfc", "-file", "soon.pem")
            runKeytool("-exportcert", "-alias", "expired", "-keystore", "expired.jks", "-storepass", STORE_PASSWORD, "-rfc", "-file", "expired.pem")

            validCertBytes = File(tempDir, "valid.pem").readBytes()
            soonCertBytes = File(tempDir, "soon.pem").readBytes()
            expiredCertBytes = File(tempDir, "expired.pem").readBytes()
            bundlePemBytes = validCertBytes + soonCertBytes

            jksBytes = File(tempDir, "valid.jks").readBytes()
            p12Bytes = File(tempDir, "test.p12").readBytes()
        }

        @AfterClass
        @JvmStatic
        fun cleanup() {
            tempDir.deleteRecursively()
        }

        private fun runKeytool(vararg args: String) {
            val command = mutableListOf(keytool)
            command.addAll(args)
            val process = ProcessBuilder(command)
                .directory(tempDir)
                .redirectErrorStream(true)
                .start()
            val output = process.inputStream.bufferedReader().readText()
            val exit = process.waitFor()
            if (exit != 0) {
                throw IllegalStateException("keytool failed (exit $exit): $output")
            }
        }
    }

    @Test
    fun parsesASingleRealCertificate() {
        val infos = CertParser.parseCertificateBundle(validCertBytes)
        assertEquals(1, infos.size)
        val info = infos[0]
        assertTrue(info.subject.contains("Valid Test Cert"))
        assertTrue(info.issuer.contains("Valid Test Cert")) // self-signed: issuer == subject
        assertEquals(ExpiryStatus.VALID, CertParser.expiryStatus(info))
        assertEquals(64, info.sha256Fingerprint.replace(":", "").length) // 32-byte SHA-256 -> 64 hex chars
    }

    @Test
    fun parsesAPemBundleWithMultipleCertificatesOneByOne() {
        val infos = CertParser.parseCertificateBundle(bundlePemBytes)
        assertEquals(2, infos.size)
        assertTrue(infos[0].subject.contains("Valid Test Cert"))
        assertTrue(infos[1].subject.contains("Expiring Soon Test Cert"))
    }

    @Test
    fun detectsExpiredCertificates() {
        val info = CertParser.parseCertificateBundle(expiredCertBytes).single()
        assertEquals(ExpiryStatus.EXPIRED, CertParser.expiryStatus(info))
    }

    @Test
    fun detectsCertificatesExpiringSoon() {
        val info = CertParser.parseCertificateBundle(soonCertBytes).single()
        assertEquals(ExpiryStatus.EXPIRING_SOON, CertParser.expiryStatus(info))
    }

    @Test
    fun opensARealJksKeystoreAndListsItsAlias() {
        val entries = CertParser.parseKeystore(jksBytes, "JKS", STORE_PASSWORD.toCharArray())
        assertEquals(1, entries.size)
        assertEquals("valid", entries[0].alias)
        assertTrue(entries[0].isPrivateKeyEntry)
        assertTrue(entries[0].cert.subject.contains("Valid Test Cert"))
    }

    @Test
    fun opensARealPkcs12Keystore() {
        val entries = CertParser.parseKeystore(p12Bytes, "PKCS12", STORE_PASSWORD.toCharArray())
        assertEquals(1, entries.size)
        assertTrue(entries[0].cert.subject.contains("PKCS12 Test Cert"))
    }

    @Test
    fun wrongKeystorePasswordFailsWithAFriendlyMessage() {
        try {
            CertParser.parseKeystore(jksBytes, "JKS", "totally-wrong-password".toCharArray())
            fail("should have thrown KeystorePasswordException")
        } catch (e: KeystorePasswordException) {
            assertTrue(e.message!!.contains("password"))
        }
    }

    @Test(expected = Exception::class)
    fun rejectsNonCertificateContent() {
        CertParser.parseCertificateBundle("this is not a certificate".toByteArray())
    }

    @Test
    fun exportsCopyablePemThatRoundTripsBackToTheSameCertificate() {
        val info = CertParser.parseCertificateBundle(validCertBytes).single()
        assertTrue(info.pem.startsWith("-----BEGIN CERTIFICATE-----"))
        assertTrue(info.pem.trim().endsWith("-----END CERTIFICATE-----"))
        val roundTrip = CertParser.parseCertificateBundle(info.pem.toByteArray()).single()
        assertEquals(info.sha256Fingerprint, roundTrip.sha256Fingerprint)
    }
}
